### ISSUE TITLE
在.env中配置了智能回复，选择了chatgpt，但是没有生效，默认还是小爱同学。还有就是智能回复插件项目地址寄了

### ISSUE THREAD

**Issue by LaffeyLa** [zhulinyv/NJS#10]
![5](https://user-images.githubusercontent.com/75292949/229364705-30e9edce-4c90-48b6-9e28-e72eac30172a.png)
这是我的配置

**Comment by zhulinyv** [comment]
已修复：
https://github.com/zhulinyv/NJS/commit/e9cb3111662d58ebe0248edcb05a097eba307b76

**Comment by LaffeyLa** [comment]
> 已修复： [e9cb311](https://github.com/zhulinyv/NJS/commit/e9cb3111662d58ebe0248edcb05a097eba307b76)

感谢，辛苦了
