### ISSUE TITLE
[建议] nonebot_plugin_wordcloud 会导致项目无法启动

### ISSUE THREAD

**Issue by dajinglingpake** [zhulinyv/NJS#11]
### 当前不足

nonebot_plugin_wordcloud 会导致项目无法启动，这个插件似乎需要手动配置数据库，我在启动时报错：
alembic.util.exc.CommandError: Can't locate revision identified by '9bca28bcb998'
经过排查发现是词云图插件初始化了nonebot_plugin_datastore插件，但是这个插件版本似乎有问题。
他需要配置alembic.ini配置文件来连接数据库，但是项目以及依赖里没有相应配置，
我不清楚它是否会自动生成一个本地数据库，所以只能先将词云图插件注释使用

### 建议内容

建议修复或者注释掉此插件

**Comment by zhulinyv** [comment]
我不确定发生了什么，建议附图上日志。

**Comment by zhulinyv** [comment]
尝试更新 https://github.com/zhulinyv/NJS/pull/12
