### ISSUE TITLE
[建议]新用户签到会返回错误值

### ISSUE THREAD

**Issue by KaMmySuma** [zhulinyv/NJS#14]
膜拜大佬~顺便把签到插件（sign_in）借来用~

我进行签到的时候返回了错误值：
  File "C:\Users\KaMmy\Desktop\bot\gocq\yuban\.\src\plugins\sign_in\__init__.py", line 29, in lj
    money = data_user[f'{qq_id}']
KeyError: '2660638311'

查看相关代码：
    # 签到
    with open(file_name) as f:
        data_user = json.load(f)
    money = data_user[f'{qq_id}']
    
似乎是没有给第一次签到的用户赋予初始好感度导致的。
赋值初始好感度后程序正常运行：
    # 签到
    with open(file_name) as f:
        data_user = json.load(f)
    if qq_id in data_user:
        money = data_user[str(qq_id)]
    else:
        money = 0  # 如果用户没有签到过，则初始好感度为0

咱是初学者，如有不对欢迎大佬指正

**Comment by zhulinyv** [comment]
https://github.com/zhulinyv/NJS/commit/5cffd0a58d4d4f58ea9af816c94a7b7cb4a1e899
try 一下

**Comment by zhulinyv** [comment]
不用提前写个 0 进去，执行签到会写入数据，再写 0 有点多余。
