### ISSUE TITLE
[问题]

### ISSUE THREAD

**Issue by kkkk24juastin** [zhulinyv/NJS#15]
### 确认

- 我的Bot版本已更新到最新，且已尝试运行 `requirements.bat` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本:unbantu22.04 
- Python版本:3.10.4 
- Nonebot2版本: 

### 问题描述

简单的描述问题发生过程或表现...
公网部署似乎无法访问。

### 问题截图
配置文件：
﻿HOST=0.0.0.0
PORT=9999
防火墙也通过了
![image](https://user-images.githubusercontent.com/99738082/233819006-0c70ab91-a040-4799-bad9-7fb11c20a58b.png)无法无法访问
![image](https://user-images.githubusercontent.com/99738082/233819012-99b2c6ab-c5db-476a-8fcb-bf6fb0871382.png)

提供问题或日志截图...
![image](https://user-images.githubusercontent.com/99738082/233819049-b6cad24f-8889-499b-90b8-2f02db0d9fba.png)

### 复现步骤

描述问题复现过程...

**Comment by zhulinyv** [comment]
参考
https://github.com/mnixry/nonebot-plugin-gocqhttp/issues/42

**Comment by zhulinyv** [comment]
_Archived, if necessary, please reopen this issue._
