### ISSUE TITLE
新的帮助

### ISSUE THREAD

**Issue by zhulinyv** [zhulinyv/NJS#20]
新的帮助，通过 json 读取帮助信息，支持添加文字、图片、md 格式文档以及支持 BBcode 形式的帮助。改用 pillow 绘制帮助图。

~~目前准备使用两个 json，一个内置，一个支持用户自定义。~~

~~内置的 json 中我将写好目前脑积水使用的全部插件的帮助。~~

~~用户自定义的 json 中可以配置想移除的内置帮助或添加额外的帮助。~~

合并为一个。

**收集建议，新的需求或建议请评论。**

![image](https://github.com/zhulinyv/NJS/assets/66541860/fdc562b8-cbf3-4c21-9ed4-48174b5f1984)

![image](https://github.com/zhulinyv/NJS/assets/66541860/3c08e107-8971-447b-9714-e67351141c69)

先画个饼，可能暑假写完。。。

![LNJO)D8~C@Y Y~0XBFG6@UX](https://github.com/zhulinyv/NJS/assets/66541860/1cae6d33-8e89-4ac9-b6f9-f4da28f31595)

**Comment by LaffeyLa** [comment]
![](https://user-images.githubusercontent.com/66541860/241384464-1cae6d33-8e89-4ac9-b6f9-f4da28f31595.jpg)

**Comment by zhulinyv** [comment]
![image](https://github.com/zhulinyv/NJS/assets/66541860/bddf174f-b8e9-46aa-94a1-809b0d774a03)

合并为一个了，新增对 BBcode 的支持。

正在往上填帮助，已经填了 40 个，还有 60 个。。。

**Comment by zhulinyv** [comment]
终于写完了 QwQ

**Comment by LaffeyLa** [comment]
> 终于写完了 QwQ

点个赞
