### ISSUE TITLE
请问这个手动狗头和没事别老发滑稽能关掉吗？

### ISSUE THREAD

**Issue by MaboroneSeika** [zhulinyv/NJS#21]
![IMG_20230530_085635](https://github.com/zhulinyv/NJS/assets/105148205/94803e98-e6c8-4cc9-a7eb-cf98da7c8474)
每次有人发这个表情都会自动发，就有点烦，想问下是哪个插件的，能不能关掉

**Comment by MaboroneSeika** [comment]
找到了，Candy_reply

**Comment by zhulinyv** [comment]
好的，以后加一个配置项

**Comment by MaboroneSeika** [comment]
> Owner

太麻烦的话就不用啦，是我没好好读手册的问题，知道是哪个插件了之后关掉加载就好了

**Comment by zhulinyv** [comment]
> > Owner
> 
> 太麻烦的话就不用啦，是我没好好读手册的问题，知道是哪个插件了之后关掉加载就好了

https://github.com/zhulinyv/NJS/commit/86c2bb22f84d4a9f9c9235dd970194ab5adf5af9

**Comment by MaboroneSeika** [comment]
> > > Owner
> > 
> > 
> > 太麻烦的话就不用啦，是我没好好读手册的问题，知道是哪个插件了之后关掉加载就好了
> 
> [86c2bb2](https://github.com/zhulinyv/NJS/commit/86c2bb22f84d4a9f9c9235dd970194ab5adf5af9)

好快wwww，多谢大佬~
