### ISSUE TITLE
No module named 'nonebot.adapters.onebot'[问题]

### ISSUE THREAD

**Issue by SkyYeXianer** [zhulinyv/NJS#22]
启动时报错No module named 'nonebot.adapters.onebot'
![image](https://github.com/zhulinyv/NJS/assets/109300803/a0038406-8408-457c-8e61-6cb74df2244a)

**Comment by zhulinyv** [comment]
检查一下依赖，可以尝试运行 `poetry install`

**Comment by SkyYeXianer** [comment]
> 检查一下依赖，可以尝试运行 `poetry install`

![image](https://github.com/zhulinyv/NJS/assets/109300803/c26e9a1e-7c22-4117-8535-29efd3eef723)
安装依赖时报错这个，我用的conda python3.10的虚拟环境，requirements.txt安装的依赖，源是清华的为什么显示没有0.2.6

**Comment by SkyYeXianer** [comment]
> > 检查一下依赖，可以尝试运行 `poetry install`
> 
> ![image](https://user-images.githubusercontent.com/109300803/244779174-c26e9a1e-7c22-4117-8535-29efd3eef723.png) 安装依赖时报错这个，我用的conda python3.10的虚拟环境，requirements.txt安装的依赖，源是清华的为什么显示没有0.2.6

解决了，换了官方源。哪些不需要的插件可以删除吗？只删除src里的插件文件就可以了吗？

**Comment by SkyYeXianer** [comment]
![image](https://github.com/zhulinyv/NJS/assets/109300803/37e1d018-8371-4738-b143-34712367e914)
这又是什么，如这个Bot的名字现在我脑积水了😭步步报错。

**Comment by SkyYeXianer** [comment]
按gpt的解释，是因为没有正确连接到数据库，是因为我用到conda而不是poetry吗？

**Comment by zhulinyv** [comment]
> > 检查一下依赖，可以尝试运行 `poetry install`
> 
> ![image](https://user-images.githubusercontent.com/109300803/244779174-c26e9a1e-7c22-4117-8535-29efd3eef723.png) 安装依赖时报错这个，我用的conda python3.10的虚拟环境，requirements.txt安装的依赖，源是清华的为什么显示没有0.2.6

清华源背大锅，在新的 pyproject.toml 中新加了其它源。

**Comment by zhulinyv** [comment]
> > > 检查一下依赖，可以尝试运行 `poetry install`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/109300803/244779174-c26e9a1e-7c22-4117-8535-29efd3eef723.png) 安装依赖时报错这个，我用的conda python3.10的虚拟环境，requirements.txt安装的依赖，源是清华的为什么显示没有0.2.6
> 
> 解决了，换了官方源。哪些不需要的插件可以删除吗？只删除src里的插件文件就可以了吗？

是的，所有插件都放在了 `./NJS/src/plugins` 中

**Comment by zhulinyv** [comment]
> 按gpt的解释，是因为没有正确连接到数据库，是因为我用到conda而不是poetry吗？

应该与这个无关

**Comment by zhulinyv** [comment]
> ![image](https://user-images.githubusercontent.com/109300803/244796286-37e1d018-8371-4738-b143-34712367e914.png) 这又是什么，如这个Bot的名字现在我脑积水了😭步步报错。

尝试删除 `./NJS/data/LittlePaimon/database` 中的所有文件，重启。

**Comment by zhulinyv** [comment]
_Archived, if necessary, please reopen this issue._
