### ISSUE TITLE
[问题]  [WinError 3] 系统找不到指定的路径。: 'data\\moegoe\\profile.toml' -> 'data\\moegoe\\profile.bak'

### ISSUE THREAD

**Issue by MaboroneSeika** [zhulinyv/NJS#23]
### 确认

- 我的Bot版本已更新到最新，且已尝试运行 `requirements.bat` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: windows11
- Python版本: 3.10.11
- Nonebot2版本: 默认

### 问题描述

运行时最后报错

### 问题截图

 nonebot | Running NoneBot...
Downloading Chromium 107.0.5304.18 (playwright build v1028) - 109.2 Mb [====================] 100% 0.0s
Chromium 107.0.5304.18 (playwright build v1028) downloaded to C:\Users\shubi\AppData\Local\ms-playwright\chromium-1028
Downloading FFMPEG playwright build v1007 - 1.4 Mb [====================] 100% 0.0s
FFMPEG playwright build v1007 downloaded to C:\Users\shubi\AppData\Local\ms-playwright\ffmpeg-1007
06-17 22:51:14 [WARNING] apscheduler | Run time of job "_restart (trigger: interval[0:00:05], next run at: 2023-06-17 22:51:18 CST)" was missed by 0:00:01.376822
06-17 22:51:25 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-P4dbqrGV-py3.10\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\software\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-P4dbqrGV-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-P4dbqrGV-py3.10\lib\site-packages\nonebot\drivers\_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\shubi\AppData\Local\pypoetry\Cache\virtualenvs\njs-P4dbqrGV-py3.10\lib\site-packages\nonebot\drivers\_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\software\NJS-Bot\src\plugins\nonebot_plugin_moegoe\__init__.py", line 58, in update
    os.rename(profilePath, bakProfilePath)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'data\\moegoe\\profile.toml' -> 'data\\moegoe\\profile.bak'

06-17 22:51:25 [ERROR] uvicorn | Application startup failed. Exiting.
### 复现步骤

在esxi8.0的all in one的虚拟机中装的，不知道是不是这个问题

**Comment by zhulinyv** [comment]
虚拟声合成插件 api 变动导致的，已修。

**Comment by MaboroneSeika** [comment]
> 

现在又有新问题了，这两天bot不会回chatgpt,openaiAPI和bing的话了，排查时候就删掉了账号重新登录，发现gocqhttp换了登录协议，但是机器人用的插件作者还没有做更换协议的功能，不知道您这边能否出个临时解决方法？比如切换到实体gocqhttp登录这种
这个：
https://github.com/mnixry/nonebot-plugin-gocqhttp/issues/614

**Comment by zhulinyv** [comment]
> > 
> 
> 现在又有新问题了，这两天bot不会回chatgpt,openaiAPI和bing的话了，排查时候就删掉了账号重新登录，发现gocqhttp换了登录协议，但是机器人用的插件作者还没有做更换协议的功能，不知道您这边能否出个临时解决方法？比如切换到实体gocqhttp登录这种 这个： [mnixry/nonebot-plugin-gocqhttp#614](https://github.com/mnixry/nonebot-plugin-gocqhttp/issues/614)

https://github.com/zhulinyv/NJS/blob/4c603f8c5bc80a16bc41cfc0e77f715e5a4624e5/pyproject.toml#L121
将此处 `"nonebot_plugin_gocqhttp"` 删除，来取消插件导入，之后你可以使用 gocqhttp 本体登录。

**Comment by MaboroneSeika** [comment]
> > > 
> > 
> > 
> > 现在又有新问题了，这两天bot不会回chatgpt,openaiAPI和bing的话了，排查时候就删掉了账号重新登录，发现gocqhttp换了登录协议，但是机器人用的插件作者还没有做更换协议的功能，不知道您这边能否出个临时解决方法？比如切换到实体gocqhttp登录这种 这个： [mnixry/nonebot-plugin-gocqhttp#614](https://github.com/mnixry/nonebot-plugin-gocqhttp/issues/614)
> 
> https://github.com/zhulinyv/NJS/blob/4c603f8c5bc80a16bc41cfc0e77f715e5a4624e5/pyproject.toml#L121
> 
> 
> 将此处 `"nonebot_plugin_gocqhttp"` 删除，来取消插件导入，之后你可以使用 gocqhttp 本体登录。

多谢大佬，顺利解决！顺带一提nonebot_plugin_gocqhttp的作者已经更新了这个加载项啦
