### ISSUE TITLE
[问题] 首次启动时因playwright问题而异常退出

### ISSUE THREAD

**Issue by Wkuny** [zhulinyv/NJS#24]
### 确认

+ 我的Bot版本已更新到最新，且已尝试运行 `requirements.bat` 更新依赖库
+ 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
+ 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决
上述问题皆以确认 已经仔细阅读readme.md
### 环境信息

- 系统版本:  Ubuntu 22.04.2 LTS x86_64
- Python版本: Python 3.10.6
- Nonebot2版本: nonebot cli version 1.1.2

### 问题描述
简单的描述问题发生过程或表现...
首次启动时因playwright的问题报错并异常退出，尝试手动安装playwright后又因为firefox不能正常安装而报错
日志和截图如下

### 问题截图
提供问题或日志截图...
首次启动时因playwright的问题报错并异常退出的日志和截图
[NJSCrash-06-27.txt](https://github.com/zhulinyv/NJS/files/11871404/NJSCrash-06-27.txt)
![image](https://github.com/zhulinyv/NJS/assets/102839847/48b540bf-fe36-47ce-a711-827fb679dab5)
尝试手动执行playwright install后又因为firefox安装异常报错
![image](https://github.com/zhulinyv/NJS/assets/102839847/2496423e-1b3f-4e28-8097-ba4684bbcb00)

### 复现步骤
描述问题复现过程...
1.尝试以poetry run python bot.py运行NJS playwright报错
2.根据报错内容执行指令poetry run playwright install又报错
此前尝试使用魔法上网 重新尝试启动NJS都没能成功
完整日志如下
[NJSCrashFull-06-27.txt](https://github.com/zhulinyv/NJS/files/11871575/NJSCrashFull-06-27.txt)

我的问题可能很lowiq  麻烦大佬们原谅，指点。谢谢。

**Comment by zhulinyv** [comment]
清空目录 /ms-playwright/，然后用 `playwright install --force` 重新安装。

**Comment by Wkuny** [comment]
已经解决playwright的问题 感谢指点
但未能正常登录
 - 不能扫码登录，强制要求输入密码
 - 最新的go-cqhttp需要一个签名服务器，已经正确部署。
 测试如图:
 - windows,linux上分别使用go-cqhttp的二进制程序直接登录，成功
![image](https://github.com/zhulinyv/NJS/assets/102839847/ab28b0c1-ea40-4037-99d0-a89966e73c16)
![截图 2023-07-04 23-46-17](https://github.com/zhulinyv/NJS/assets/102839847/5a51f30b-b541-4ebd-a131-b9db78ba35e8)
 - 页面上登录，失败
![截图 2023-07-04 23-47-03](https://github.com/zhulinyv/NJS/assets/102839847/1fec9613-c709-458e-a496-5f4bb2d7b020)

 - 覆盖修改配置文件（使用已经在windows下成功登录的覆盖config.yml和device.json及其余两个目录），用go-cqhttp的最新linux二进制程序覆盖NJS/accounts/binary/下的相应二进制程序 后均无果。
 - 经多次尝试后均发现配置页面上修改账号和设备信息后，修改不能被正确应用，发现一些关键配置（例如 签名服务器地址）被删去。
望指点

谢谢大佬

**Comment by Wkuny** [comment]
额 session.token也拖过去了 都没用
还把我号风控了

**Comment by Wkuny** [comment]
玄学 在一次瞎折腾之后已经完成部署了 谢谢指点
