### ISSUE TITLE
🐛额..今天更新后又遇到新问题，在群里不管发什么都收不到回复

### ISSUE THREAD

**Issue by MaboroneSeika** [zhulinyv/NJS#27]
### 确认

- 我的Bot版本已更新到最新，且已尝试运行 `poetry install` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: 
- Python版本: 310
- Nonebot2版本: 默认

### 问题描述

换了新的QQ号，用了dev的gocq和1.1.6的签名

### 问题截图

日志开了info，可以看到收到群聊以后会有一条“Event message.group.normal is ignored”

### 复现步骤

如题，任何群的任何消息都是石沉大海

**Comment by zhulinyv** [comment]
无法复现，请上传完整日志文件或截图。

已在频道回复，某些插件会阻断消息传播，请留意。

**Comment by MaboroneSeika** [comment]
放置了一天，莫名其妙好了，怀疑是QQ新号的问题~
