### ISSUE TITLE
apibug.cn域名已经更换🐛

### ISSUE THREAD

**Issue by Apibug** [zhulinyv/NJS#29]
apibug.cn域名已经更换
为：api.apibug.com

**Comment by zhulinyv** [comment]
是文档中小爱同学对话的 api 嘛

**Comment by Apibug** [comment]
是的，我搜索看到了，域名已经换了

**Comment by zhulinyv** [comment]
实际上代码中并没有使用这个 api，只是文档没来得及更新
但是代码中使用的 api 也寄了，找不到稳定的小爱聊天 api
目前默认使用的是青云客 api，后续会将原本的小爱 api 改为 [apibug](https://apibug.cn/)

**Comment by zhulinyv** [comment]
@Apibug 已更换, 感谢提供 api
