### ISSUE TITLE
我用了新的对话插件，现在我该如何关闭原有的NJS聊天功能？[问题]标题

### ISSUE THREAD

**Issue by tuhuahu123** [zhulinyv/NJS#3]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.9.10
- Nonebot2版本: 2.0.0rc2

### 问题描述

简单的描述问题发生过程或表现...

### 问题截图

提供问题或日志截图...

### 复现步骤[可选]

描述问题复现过程...

**Comment by zhulinyv** [comment]
可以直接发送 “npm block nonebot_plugin_smart_reply”，在线关闭，或者将 ./src/plugin/nonebot_plugin_smart_reply 目录下的 __init__.py 改名为 init__.py 取消加载该插件。

**Comment by zhulinyv** [comment]
_Archived, if necessary, please reopen this issue._
