### ISSUE TITLE
🐛访问GOCQ网站显示{"detail": "Not Found"}

### ISSUE THREAD

**Issue by xiaonengya** [zhulinyv/NJS#30]
### 确认

- 我的Bot版本已更新到最新，且已尝试运行 `poetry install` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Window11专业版23H2
- Python版本: 3.10.11
- Nonebot2版本: 最新版

### 问题描述

简单的描述问题发生过程或表现...
在初始化完成之后就会卡住，然后此时访问GOCQ网站就会出现

**Comment by zhulinyv** [comment]
由于不可抗力因素, gocq-http 已经是过去式了, 脑积水已经移除了内置的 gocq-http 插件, 请查看自述文件中推荐的项目, 或自行查找其它项目

https://github.com/zhulinyv/NJS#9%EF%B8%8F%E2%83%A3-%E7%99%BB%E5%BD%95-%E8%84%91%E7%A7%AF%E6%B0%B4

**Comment by xiaonengya** [comment]
那么监听的端口应该设为什么

**Comment by xiaonengya** [comment]
我有一个可以使用的goCQ，请问我如何设置它的监听地址

**Comment by zhulinyv** [comment]
在 gocq 生成的配置文件中找到 universal, 并修改其值为 `ws://127.0.0.1:13579/onebot/v11/ws`

例如: `universal: "ws://127.0.0.1:13579/onebot/v11/ws"`

13579 是脑积水默认的端口号, 如果在 .env.prod 中修改为其它, 请替换上方的 13579
