### ISSUE TITLE
🐛语音返回有问题

### ISSUE THREAD

**Issue by xiaonengya** [zhulinyv/NJS#31]
### 确认

- 我的Bot版本已更新到最新，且已尝试运行 `poetry install` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Window11专业版23H2
- Python版本: 3.10.11
- Nonebot2版本: 最新版

### 问题描述

戳一戳会触发

### 问题截图

[CQ:record,file=file:///D:/NJS-Bot/src/plugins/smart_reply/resource/audio/%E4%BD%A0%E5%AF%84%E5%90%A7%E8%B0%81%E5%95%8A%28%E6%8C%AF%E5%A3%B0%21%29.aac,magic=,cache=,proxy=,timeout=]

### 复现步骤

戳一戳

**Comment by zhulinyv** [comment]
消息处理的客户端还是使用的 go-cqhttp 嘛, 如果不是, 可能使用的客户端已经不支持 CQ 码

**Comment by xiaonengya** [comment]
还是使用gocq

**Comment by zhulinyv** [comment]
我没有办法复现这个问题, 因为我的 gocq 已经无法登录

**Comment by xiaonengya** [comment]
如何进行管理员操作,管理所加群或者管理加群批准

**Comment by zhulinyv** [comment]
NJS 中没有同意入群功能, 因为这和自带的 Q 群管家功能重复, 并且 Q 群管家提供了筛选条件, 功能更加实用,

如果需要禁言或移除群成员可以查看内置群管插件的文档, 注意请将模式设为 2 https://github.com/zhulinyv/nonebot_plugin_easy_group_manager
