### ISSUE TITLE
🐛如何管理或更新LittlePaimon

### ISSUE THREAD

**Issue by xiaonengya** [zhulinyv/NJS#32]
### 确认

- 我的Bot版本已更新到最新，且已尝试运行 `poetry install` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/NJS#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/NJS/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Window11专业版23H2
- Python版本: 3.10.11
- Nonebot2版本: 最新版

### 问题描述

询问如何更新或管理此插件

### 问题截图

提供问题或日志截图...

### 复现步骤

描述问题复现过程...

**Comment by zhulinyv** [comment]
需要手动替换相应文件, 由于里面我改了一部分文件, 替换时注意合并修改, 原本我大概每两周更新一次的, 不过我现在很少维护这个项目了
