### ISSUE TITLE
[问题]启动过程中发现有关json读取部分报错怎么解决

### ISSUE THREAD

**Issue by whycantlog** [zhulinyv/NJS#5]
![@ }D3N4WEP$Q4L9P`_Z% 0L](https://user-images.githubusercontent.com/49138644/227849959-94a3231f-f013-477b-bd9f-e5ffd68b95e5.png)

**Comment by zhulinyv** [comment]
疯狂星期四的 json 下载源更换，可以先将 .\src\plugins\nonebot_plugin_crazy_thursday 目录下的 __init__.py 改名为 init__.py 取消加载该插件。

周末回家修复 QwQ 。

**Comment by zhulinyv** [comment]
https://github.com/zhulinyv/NJS/pull/6
